import type {RowDescriptor} from "../../../shared/types/RowDescriptor.ts";


export const TimesheetLeaves: RowDescriptor[] = [
    { key: "FormationIA", label: "Formation IA" },
    { key: "LabourAdvisor", label: "Conseiller Prud’Homal" },
    { key: "Vacation", label: "Vacances (Congés payés)" },
    { key: "CompTime", label: "Temps compensatoire" },
    { key: "SickLeave", label: "Maladie" },
    { key: "ExamLeave", label: "Congé pour examen / etudes" },
    { key: "MovingLeave", label: "Congé déménagement" },
    { key: "BereavementLeave", label: "Congé pour décès famille" },
    { key: "WorkAccident", label: "Accident de travail" },
    { key: "JuryWitnessLeave", label: "Congé pour juré/témoin" },
    { key: "MarriageLeave", label: "Congé mariage/PACS" },
    { key: "PaternityLeave", label: "Congé de paternité" },
    { key: "BirthLeave", label: "Congé naissance enfant" },
    { key: "FamilySolidarityLeave", label: "Congé solidarité familiale" },
    { key: "AdministrativeLeave", label: "Congé administratif" },
    { key: "GradualReturn", label: "Retour progressif au travail" },
    { key: "UnauthorizedAbsence", label: "Absc non autoriséee non payée" },
    { key: "UnpaidLeave", label: "Congé sans solde" },
    { key: "PrenatalExamLeave", label: "Congé examen prénatal" },
    { key: "MarriageChildLeave", label: "Congé mariage/PACS enfant" },
    { key: "PaidParentalLeave", label: "Congé de parentalité payé" },
    { key: "UnpaidParentalLeave", label: "Congé de parentalité non payé" },
    { key: "TemporaryWork", label: "Travaux passagers" },
    { key: "PreSales", label: "Avant-vente" },
    { key: "GeneralAdmin", label: "Général et administration" },
    { key: "PartTimeComplement", label: "Compl temps partiel / activite" },
    { key: "Training", label: "Formation" },
    { key: "TrainingAnimation", label: "Formation Animation" },
    { key: "Holiday", label: "Jour férié" },
    { key: "RTTQ1", label: "RTT Q1" },
    { key: "RTTUnpaidQ2", label: "RTT non payée (Q2)" },
    { key: "SickChildAlsaceMoselle", label: "Enfant malade Alsace-Moseille" },
    { key: "LeaveDonation", label: "Bénéficiaire don de congé" },
    { key: "UnpaidAuthorizedAbsence", label: "Abs. autorisée non rémunérée" },
    { key: "CPFVAEPaid", label: "CPF/VAE/Bilan compé. Payé" },
    { key: "CPFVAEUnpaid", label: "CPF/VAE/Bilan compé. non payé" },
    { key: "OccupationalDisease", label: "Maladie professionnelle" },
    { key: "CommutingAccident", label: "Accident de trajet" },
    { key: "PrenatalPatho", label: "Grossesse patho. pré-natale" },
    { key: "PostnatalPatho", label: "Grossesse patho. post-natale" },
    { key: "StateElected", label: "Elu d'état" },
    { key: "JobSearchLeave", label: "Congé recherche d'emploi" },
    { key: "TravelHours", label: "Heures déplacements récup" },
    { key: "SpecialDispense", label: "Dispense Spe Rem" },
    { key: "WeeklyDailyRest", label: "Repos Hebdo/Quotidien" },
    { key: "AccompanimentLeave", label: "Congé d'accompagnement" },
    { key: "ChildPathoHandicap", label: "Enfant – Annonce patho/handi" },
    { key: "HandicapCare", label: "Soin handicap" },
    { key: "UnionTraining", label: "Formation syndicale (CFESES)" },
    { key: "RQTHFile", label: "RQTH - Dossier" },
    { key: "PDPMA", label: "PDPMA" },
    { key: "CETDays", label: "Jours CET" },
    { key: "SocialSecurityRepresentative", label: "Mandataire sécurité sociale" },
    { key: "RetirementCET", label: "CET Retraite" },
    { key: "BereavementParentalLeave", label: "Congé deuil parental" },
    { key: "ParentRequiredUnder12", label: "Prés. parent requis enf<12 ans" },
    { key: "HospitalizedChildLeave", label: "Congé enfant hospitalisé" },
    { key: "SkillSponsorship", label: "Mécénat de compétences" },
    { key: "SpontaneousPregnancyInterruption", label: "Interr spontanée de grossesse" },
    { key: "EmployeeAdvisor", label: "Conseiller du salarié" },
    { key: "TrainingCPH", label: "Congé Formation conseiller CPH" },
    { key: "UnionDefender", label: "Défenseur syndical" },
    { key: "UnionDefenderTraining", label: "Formation Défenseur syndical" },
    { key: "SickChildUnpaid", label: "Congé enfant malade non payé" },
    { key: "JudicialAssessor", label: "Assesseur judiciaire SS" },
    { key: "MilitaryPoliceUnpaid", label: "Abs. militaire/police non payé" },
    { key: "MilitaryPolicePaid", label: "Congé militaire/police payé" },
];
